trigger:
  branches:
    include:
    - irinasp/mirror_github

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: GarnetGithubRepo
    type: github
    name: microsoft/garnet
    endpoint: ADO_to_Github_ServiceConnection
    trigger:
      branches:
        include:
        - irinasp/mirror_github

jobs:
- job: MirrorGithubToADO
  displayName: 'Mirror Github to Azure DevOps'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: GarnetGithubRepo
    clean: true
    persistCredentials: true

  - script: |
      # Set up Git identity  
      git config user.email "$(GIT_USER_EMAIL)"
      git config user.name "$(GIT_USER_NAME)"

      # Reset to main branch to ensure it's up-to-date
      git fetch origin irinasp/mirror_github
      git checkout irinasp/mirror_github
      git reset --hard irinasp/mirror_github

      # Push to Azure DevOps Repository
      git push https://dev.azure.com/msresearch/_git/Garnet irinasp/mirror_github

    displayName: 'Push to Azure DevOps'
    env:
      GIT_USER_EMAIL: $(GIT_USER_EMAIL)
      GIT_USER_NAME: $(GIT_USER_NAME)
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)