<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../libs/host/Garnet.host.csproj" />
    <ProjectReference Include="../libs/server/Garnet.server.csproj" />
    <ProjectReference Include="../libs/common/Garnet.common.csproj" />
    <ProjectReference Include="../libs/storage/Tsavorite/cs/src/core/Tsavorite.core.csproj" />
  </ItemGroup>
</Project>
