name: Bug report
description: File a bug report
title: "Bug title"
labels: []
body: 
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: textarea
    attributes:
      label: Release version
      description: Please input release version
      placeholder: |
        v1.0.5
  - type: textarea
    attributes:
      label: IDE
      description: Which IDE versions did you see the issue on?
      placeholder: |
        Visual Studio 2026
  - type: textarea
    attributes:
      label: OS version
      description: Which OS versions did you see the issue on?
      placeholder: |
        Windows 11 (22000)
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
