{{- if and (eq .Values.config.existingSecret "") .Values.config.garnetConf }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garnet.fullname" . }}-config
  labels:
    {{- include "garnet.labels" . | nindent 4 }}
type: Opaque
data:
  garnet.conf: {{ .Values.config.garnetConf | b64enc | quote }}
{{- end }}
