apiVersion: v1
kind: Service
metadata:
  name: {{ include "garnet.fullname" . }}-headless
  labels:
    {{- include "garnet.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
      name: garnet
  selector:
    {{- include "garnet.selectorLabels" . | nindent 4 }}
