{{- if and .Values.serviceAccount.create .Values.serviceAccount.token (semverCompare ">=1.24-0" .Capabilities.KubeVersion.GitVersion) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garnet.serviceAccountName" . }}-token
  labels:
    {{- include "garnet.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "garnet.serviceAccountName" . }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
