# Benchmark configuration
# Lines starting with # are comments

# SSH connection
SshUser=guser
ClientMachineCount=[4]
ClientMachineHostnames=[vm0.client16core.southcentralus.cloudapp.azure.com]
Multiplier=1

# Benchmark parameters
Server=10.5.128.4
Port=7000
Threads=16
Runtime=15
ClusterBench=true

# Use a connection pool for every worker
# If not set to true every benchmark instance wii create a single connection per shard per thread
# e.g shards = 6, threads = 8 => 48 workers/connections
Pool=true
# Broadcast requests across collection pool for every worker and wait for response
Broadcast=false

# Operation type (optional, e.g., GET, SET, MGET, MSET)
Op=SET

# Data parameters
DbSize=13514
KeyLength=8
ValueLength=100
BatchSize=4096

# Additional arguments (optional)
ExtraArgs=--replica-ops-percent 0 --offline-buffers 128
