# Benchmark configuration
# Lines starting with # are comments

# SSH connection
SshUser=guser
ClientMachineCount=[1]
ClientMachineHostnames=[vm0.d128ldsv6read.canadaeast.cloudapp.azure.com]
Multiplier=1

# Benchmark parameters
Server=10.5.128.11
Port=7000
Threads=128
Runtime=15000
ClusterBench=true

# Use a connection pool for every worker
# If not set to true every benchmark instance wii create a single connection per shard per thread
# e.g shards = 6, threads = 8 => 48 workers/connections
Pool=true
# Broadcast requests across collection pool for every worker and wait for response
Broadcast=false

# Operation type (optional, e.g., GET, SET, MGET, MSET)
Op=GET

# Data parameters
DbSize=10485760
#DbSize=1024
KeyLength=8
ValueLength=8
BatchSize=4096

# Additional arguments (optional)
ExtraArgs=--replica-ops-percent 100
