<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../../Garnet.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libs\client\Garnet.client.csproj" />
    <ProjectReference Include="..\..\libs\host\Garnet.host.csproj" />
    <ProjectReference Include="..\..\libs\server\Garnet.server.csproj" />
    <ProjectReference Include="..\..\metrics\HdrHistogram\HdrHistogram.csproj" />
  </ItemGroup>

</Project>
