name: Garnet Docker images for Windows

on:
  workflow_dispatch: # allow manual run
  workflow_run:
    workflows: ['Garnet .NET CI']
    types: [completed]
    branches: [main]
  push:
    tags: 'v*'

permissions:
   contents: read
   packages: write

jobs:
  docker:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6 for security reasons have pinned tag (commit SHA) for 3rd party
        with:
          images: ghcr.io/${{ github.repository }}-nanoserver-ltsc2022
          tags: |
            # generate Docker tags based on the following events/attributes
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4 for security reasons have pinned tag (commit SHA) for 3rd party
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push
        if: ${{ (github.ref_name == 'main' || (github.ref_type == 'tag' && startsWith(github.ref_name, 'v'))) && github.event_name != 'pull_request' }}
        run: |
          docker build -f Dockerfile.nanoserver `
            --tag ${{ fromJSON(steps.meta.outputs.json).tags[0] }} `
            --tag ${{ fromJSON(steps.meta.outputs.json).tags[1] }} `
            --tag ${{ fromJSON(steps.meta.outputs.json).tags[2] }} .
          docker push ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          docker push ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
          docker push ${{ fromJSON(steps.meta.outputs.json).tags[2] }}

      - name: Build Only
        if: ${{ !((github.ref_name == 'main' || (github.ref_type == 'tag' && startsWith(github.ref_name, 'v'))) && github.event_name != 'pull_request') }}
        run: |
          docker build -f Dockerfile.nanoserver .
