name: Garnet Helm Chart

on:
  workflow_dispatch: # allow manual run
  push:
    branches:
      - main
    paths:
      - 'charts/**/Chart.yaml'
      - 'charts/**/templates/**'
      - 'charts/**/values*'
      - 'charts/**/README.md.gotmpl'

permissions:
  contents: read
  packages: write

jobs:
  helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.0 for security reasons we have pinned the tag (commit SHA) for 3rd party
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install helm-docs
        env:
          HELM_DOCS_VERSION: "1.14.2"
          HELM_DOCS_SHA256: "a8cf72ada34fad93285ba2a452b38bdc5bd52cc9a571236244ec31022928d6cc"
        run: |
          set -euo pipefail

          cd /tmp
          FILENAME="helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz"
          wget "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/${FILENAME}"
          
          echo "${HELM_DOCS_SHA256}  ${FILENAME}" | sha256sum -c -
          
          tar -xvf "${FILENAME}"
          sudo mv helm-docs /usr/local/bin

      - name: Verify chart metadata
        run: |
          set -euo pipefail
          VERSION_PROPS=$(awk -F'[<>]' '/<VersionPrefix>/{print $3}' Version.props | tr -d '\n')
          CHART_APP_VERSION=$(awk '$1 == "appVersion:" {print $2}' charts/garnet/Chart.yaml)

          if [[ "${CHART_APP_VERSION}" != "${VERSION_PROPS}" ]]; then
            echo "Chart appVersion (${CHART_APP_VERSION}) must match Version.props (${VERSION_PROPS})"
            exit 1
          fi

      - name: Helm lint, helm-docs and helm package
        run: |
          set -euo pipefail
          mkdir .cr-release-packages
          while IFS= read -r -d '' chart; do
            helm lint "${chart}"
            helm-docs --document-dependency-values --chart-search-root "${chart}"
            helm package "${chart}" --dependency-update --destination .cr-release-packages
          done < <(find charts -mindepth 1 -maxdepth 1 -type d -print0)

      - name: Login to GHCR
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "${GITHUB_TOKEN}" | helm registry login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/helm-charts"
          done
