name: Garnet Nightly Tests
on:
  schedule:
    - cron:  '0 9 * * *' # Runs at 09:00 UTC, which is 1:00 AM PST
  workflow_dispatch:
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  contents: read
  
jobs:
  build-test-garnet:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025 ]
#        framework: [ 'net8.0', 'net9.0' ]
#        configuration: [ 'Debug', 'Release' ]
        os: [ windows-2025 ]
        framework: [ 'net9.0' ]
        configuration: [ 'Release' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set workaround for libaio on Ubuntu 24.04 (see https://askubuntu.com/questions/1512196/libaio1-on-noble/1512197#1512197)
        run: |
          sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
        if: ${{ matrix.os == 'ubuntu-24.04' }}        
      - name: Set environment variable for Linux
        run: echo "RunAzureTests=yes" >> $GITHUB_ENV
        if: ${{ matrix.os == 'ubuntu-24.04' }}
      - name: Set environment variable for Windows
        run: echo ("RunAzureTests=yes") >> $env:GITHUB_ENV
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js for Azurite
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Run Azurite
        shell: bash
        run: |
          npm install -g azurite
          azurite &

      - name: Install dependencies
        run: dotnet restore

      - name: Build Garnet
        run: dotnet build --configuration ${{ matrix.configuration }}

      - name: Build and Run Garnet Tests
        if: ${{ always() }}
        shell: bash
        run: |
            dotnet build test/Garnet.test --configuration ${{ matrix.configuration }}
            dotnet test test/Garnet.test -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"

      - name: Build and Run Tsavorite Tests
        if: ${{ always() }}
        shell: bash
        run: |
            dotnet build libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj --configuration ${{ matrix.configuration }}
            dotnet test libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"

      - name: Build and Run Cluster Tests
        if: ${{ always() }}
        shell: bash
        run: |
            dotnet build test/Garnet.test.cluster --configuration ${{ matrix.configuration }}
            dotnet test test/Garnet.test.cluster -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-garnet-results-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          path: TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}

#      - name: Install Allure and Generate Report (Windows only)
#        if: runner.os == 'Windows' && always()
#        run: |
#          iex "& {$(irm get.scoop.sh)}"
#          scoop install allure
#          scoop bucket add extras
#          $env:PATH += ";$env:USERPROFILE\scoop\apps\allure\current\bin"
#          Copy-Item "categories.json" "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}" -Force
#          allure generate "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}" --clean -o build/allure-report/allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}

#      - name: Install Allure and Generate Report (Linux only)
#        if: runner.os == 'Linux' && always()
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y build-essential curl file git
#          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
#          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
#          brew install allure
#          cp categories.json "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
#          allure generate "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}" --clean -o build/allure-report/allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}

#      - name: Verify Allure Report Output
#        if: always()
#        run: |
#          dir build/allure-report/allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          
#      - name: Upload Allure Report Artifact
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
#          path: build/allure-report

  merge-results-and-generate-report:
    name: Merge Results & Generate Unified Allure Report
    runs-on: windows-2022
    needs: build-test-garnet
    if: always()
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download all test result artifacts
        uses: actions/download-artifact@v4
        with:
          path: merged-results

      - name: Collect .trx files into one directory
        if: always()
        run: |
          mkdir final-results
          Get-ChildItem -Recurse -Filter *.trx -Path merged-results | ForEach-Object {
            Copy-Item $_.FullName -Destination final-results
          }
          dir final-results  
          
      - name: Copy categories.json
        if: always()
        run: |
          Copy-Item categories.json final-results -Force

      # DEBUG - a test to see if history already being checked in can be copied to the final results 
      # DEBUG - for now the saved history folder is in root ... maybe move it all to a different folder if going to go with this   
      - name: Copy checked-in history folder to final-results
        if: always()
        continue-on-error: true
        shell: pwsh
        run: |
          $source = "history"
          $target = "final-results/history"
          dir $source

          Write-Host "Copying checked-in history from $source to $target"

          if (Test-Path $source) {
              New-Item -ItemType Directory -Force -Path $target
              Copy-Item "$source/*" -Destination $target -Recurse -Force
              Write-Host "History copied successfully"
              dir $target -Recurse
          } else {
              Write-Host "No history folder found in repo"
          }

      # TO DO: GitHub Actions doesn't support referring back to previous history - so need to check it in or something
      # TO DO: Problem is that there are thousands of test cases
#      - name: Download previous history from artifacts
#        if: always()
#        continue-on-error: true
#        uses: actions/download-artifact@v4
#        with:
#          name: allure-history
#          path: previous-history

#      - name: Restore history
#        if: always()
#        shell: pwsh
#        run: |
#          $source = "previous-history"
#          $target = "final-results/history"

#          Write-Host "Contents of previous-history before restore:"
#          dir $source -Recurse
          
#          New-Item -ItemType Directory -Force -Path $target

#          if (Test-Path "$source") {
#              Copy-Item "$source/*" -Destination $target -Recurse -Force
#          } else {
#              Write-Host "No previous history found"
#          }
#          Write-Host "Contents of final-results/history after restore:"
#          dir $target -Recurse

      - name: Install Allure and Generate the Report
        if: always()
        run: |
          iex "& {$(irm get.scoop.sh)}"
          scoop install allure
          scoop bucket add extras
          $env:PATH += ";$env:USERPROFILE\scoop\apps\allure\current\bin"
          allure -v generate final-results --clean -o final-report --single-file
          dir final-report -Recurse

      - name: Upload Unified Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unified-allure-report
          path: final-report

      # TO DO:  Can upload it but GitHub Actions doesn't support referring back to previous history
#      - name: Upload Allure history to Artifacts for next run
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          path: final-report/history
