name: Garnet Nightly Tests
on:
  schedule:
    - cron:  '0 9 * * *' # Runs at 09:00 UTC, which is 1:00 AM PST
  workflow_dispatch:
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  contents: read
  
jobs:
  build-test-garnet:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # test: [ 'Garnet.test', 'Garnet.test.cluster', 'Tsavorite.test' ]
        os: [ ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025 ]
        framework: [ 'net8.0', 'net9.0' ]
        configuration: [ 'Debug', 'Release' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set workaround for libaio on Ubuntu 24.04 (see https://askubuntu.com/questions/1512196/libaio1-on-noble/1512197#1512197)
        run: |
          sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
        if: ${{ matrix.os == 'ubuntu-24.04' }}        
      - name: Set environment variable for Linux
        run: echo "RunAzureTests=yes" >> $GITHUB_ENV
        if: ${{ matrix.os == 'ubuntu-24.04' }}
      - name: Set environment variable for Windows
        run: echo ("RunAzureTests=yes") >> $env:GITHUB_ENV
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js for Azurite
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Run Azurite
        shell: bash
        run: |
          npm install -g azurite
          azurite &

      - name: Install dependencies
        run: dotnet restore

      - name: Check style format
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Build Garnet
        run: dotnet build --configuration ${{ matrix.configuration }}


      #- name: Build and Run Tests ${{ matrix.test }}
      #  shell: bash
       # run: |
        #  if [ "${{ matrix.test }}" = "Tsavorite.test" ]; then
         #   dotnet build libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj --configuration ${{ matrix.configuration }}
          #  dotnet test libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.test }}-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
          #else
            #dotnet build test/${{ matrix.test }} --configuration ${{ matrix.configuration }}
            #dotnet test test/${{ matrix.test }} -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.test }}-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
          #fi
      - name: Build and Run Tests
        shell: bash
        run: |
            dotnet build libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj --configuration ${{ matrix.configuration }}
            dotnet test libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
            dotnet build test/Garnet.test --configuration ${{ matrix.configuration }}
            dotnet test test/Garnet.test -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
            dotnet build test/Garnet.test.cluster --configuration ${{ matrix.configuration }}
            dotnet test test/Garnet.test.cluster -f ${{ matrix.framework }} --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"



      - name: Install Allure and Generate Report (Windows only)
        if: runner.os == 'Windows' && always()
        run: |
          iex "& {$(irm get.scoop.sh)}"
          scoop install allure
          scoop bucket add extras
          $env:PATH += ";$env:USERPROFILE\scoop\apps\allure\current\bin"
          allure --version
          dir
          Copy-Item "categories.json" "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}" -Force
          allure --version
          dir TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          allure generate "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}" --clean -o build/allure-report/allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}

      - name: Install Allure and Generate Report (Linux only)
        if: runner.os == 'Linux' && always()
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install allure
          allure --version
          pwd
          ls
          cp categories.json "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
          allure --version
          ls TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          allure generate "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}" --clean -o build/allure-report/allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}

      - name: Verify Allure Report Output
        if: always()
        run: |
          dir build/allure-report/allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          
      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          path: build/allure-report

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-garnet-results-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
          path: TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}
        if: ${{ always() }}
